### PR TITLE
Modified Plot finder.py and updated .gitignore to exclude Vim swap files

### PR DESCRIPTION
**Pull request by UDAYA-0504**

### CODE REVIEW

**Review by UDAYA-0504 — COMMENTED** [review]
Changes:

Modified: Updated the Plot finder.py script to improve functionality or fix issues (specify more detail about what was changed if possible).
Updated .gitignore: Added entries for excluding Vim temporary files (*.swp, *.swo) to prevent them from being tracked in Git.

Reason:

The .gitignore update ensures that temporary files generated by Vim won't be committed, keeping the repository clean.
The changes in Plot finder.py improve the script (could specify further if it's a bug fix or a feature enhancement).

**Comment by almsam** [comment]
git ignore files changed - well done on that front, but im unsure why ``` func_str = input("Enter a function (e.g., '2*x**2 + 4*x + 1'): ")``` was changed to ``` func_str =eval(input("Enter a function (e.g., '2*x**2 + 4*x + 1'): ")) ```

**Comment by almsam** [comment]
no bugs remain, no merge conflict - merging time

**Comment by almsam** [comment]
merge to main successful, PR closed

**Pull request merged**
