### PR TITLE
Cleaned up and did some simple bug fixing

### PR DESCRIPTION
**Pull request by Spunchkin**
Cleaned up some of the code where I could, and added some minor changes that could fix some potential bugs with Undefined values and such, if any bugs arise due to these changes I will attempt to fix them urgently!

### CODE REVIEW

**Comment by Spunchkin** [comment]
Let me know if this doesn't work the same as the original, I had less than enough time to test it myself

**Review by almsam — COMMENTED** [review]
looks good to me - well done

**Comment by almsam** [comment]
will test shortly before merging

**Comment by almsam** [comment]
revision needed: Loess regression doesn't work, I will revert to previous solution for this one

**Comment by almsam** [comment]
another error found, this was on me but logistic regression wasn't supposed to be used here as that is for classifying multimodal datasets - not continuous predictions - ill remove it & commit the updated version shortly

**Comment by almsam** [comment]
both changes commited & pushed, no merge conflicts, merging

**Comment by almsam** [comment]
megred, great work, thanks for the help

**Pull request merged**
